version: '3'

services:
  vpn:
    build: ./.
    image: enno0815de/strongswan-fb
    env_file:
      - ./config.env
    restart: always
    volumes:
        - /lib/modules:/lib/modules
        - /etc/localtime:/etc/localtime
    ports:
     - "500:500"
     - "4500:4500"
    tmpfs: /run
    privileged: yes
    networks:
      vpn-fb:
        ipv4_address: 192.168.42.10

networks:
    vpn-fb:
      driver: bridge
      ipam:
       config:
         - subnet: 192.168.42.0/24
           gateway: 192.168.42.1